docs_dir: docs/book
site_dir: docs/html
extra:
  project: Packages
  current_version: v3
  versions:
    - v3
nav:
  - Home: index.md
  - v4:
      - "Adding The Config Provider": v3/addingConfigProvider.md
      - "Configuring the writer(s)": v3/configuringWriter.md
      - "Grouping log files by date": v3/groupingLogFilesByDate.md
      - "Filtering log messages": v3/filteringLogMessages.md
      - "Formatting Messages": v3/formattingMessages.md
      - "Usage": v3/usage.md
site_name: dot-log
site_description: "DotKernel log component extending and customizing"
repo_url: "https://github.com/dotkernel/dot-log"
plugins:
  - search
